package com.sintel.cantiquesenmafa

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ListView
import androidx.fragment.app.Fragment


class CantiquesFragment : Fragment() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val root= inflater.inflate(R.layout.fragment_cantiques, container, false)

        var listView =root.findViewById<ListView>(R.id.liste_cantiques)
        val chantAdapter = container?.context?.let { ChantAdapter(it, Titre_cantique) }
        listView.adapter=chantAdapter

        listView.setOnItemClickListener{ parent, view, position, id ->
            val intent = Intent(getActivity(),CantiqueActivity::class.java)
            intent.putExtra("position",position)
            startActivity(intent)
        }

        return root
    }


     val Titre_cantique= arrayOf (
        "1 Aman nga co Yèsu a ndav nga ma",
        "2 Pombi Bi m’mbel nga",
        "3 A pats a vaɗ ka takaha nga",
        "4 Bab Zhiklè, i slébèrdè ka",
        "5 Bai Yèsu, kra Zhiklè	",
        "6 Do a sam Yèsu	",
        "7 War a ka co !	",
        "8 Ma Zhiklè a ndiv azɓai	",
        "9 Nzlembaɗ mbela’a gar Yèsu	",
        "10 I sun a vava	",
        "11 Yèsu a gaɗa : Vo-washkè arna	",
        "12 Civèɗ mbela’a	",
        "13 Yèsu a nco wof ngézlèl na	",
        "14 Sam a zhè te zhiklè te géɗè’a	",
        "15 Yèsu a zhè a nshèffè	",
        "16 Nga wuffè a civèɗ Yèsu	",
        "17 Bai Yèsu a di a shkè deɓa	",
        "18 Slambaɗa, do a sam nhela’a	",
        "19 Yèsu Kristi a zhè a woy ka	",
        "20 I mana ndav ga	",
        "21 Zhiklè ngu maya	",
        "22 Zlèzlè’a nga gu ɓèl malai	",
        "23 Te nhér gèɗ ga	",
        "24 Ka woya njèkeda mali ngaya dè ?	",
        "25 Yèsu a hel sam herkeda	",
        "26 Mali ngaya ntila ma ɗè ?	",
        "27 Va-vau	",
        "28 Ndav ga wuffè	",
        "29 Pombi herkeda	",
        "30 Yèsu a mbad pombaz a hai	",
        "31 Wa bab ga, washkè	",
        "32 N’azɓai a mpèn ndav ngaya	",
        "33 Pats n’ndev matakwan ga t’herkeda	",
        "34 Nza a nda nga	",
        "35 Yèsu Kristi, pombaz ngaya	",
        "36 I war i ngreda mali ga auda	",
        "37 M’mbel nga ma	",
        "38 I sun woyam staɗ a iyam mbela’a	",
        "39 A gèɗ pombi man a ndiv azɓai	",
        "40 Wof ngézlèlè a Yèsu Krist	",
        "41 Yèsu ndo madzaf nzura’a	",
        "42 I mana ndav ga	",
        "43 Ka gu zlau ɓai, Zhiklè woy ka	",
        "44 Nga wuffè a géɗ Zhiklè	",
        "45 Ɗakwa, gol Yèsu, ka zlatsahi ɓai !	",
        "46 Man tolom Zhiklè a ɓica nga	",
        "47 Ka te zhiklè, i t’herkeda	",
        "48 Man ka woya ka ngècè nshèffè mbia’a	",
        "49 Zhiklè nzlündo Yèsu a herkeda	",
        "50 I jèjèr sak Yèsu	",
        "51 Mandal ga washkè co ma Zhiklè	",
        "52 Bab ga te géɗè’a, i da pca ka a gèɗ ɓai	",
        "53 Na haha kra tambak Zhiklè	",
        "54 I sun ɓai èhèmè i mbel ga	",
        "55 Alleluya, slu dimèsh a sam Yèsu	",
        "56 Bab nga Zhiklè a bèhè	",
        "57 Washkè, ngo-dokona, a gi Bab nga	",
        "58 Mpi ndohi Zhiklè tèlèba	",
        "59 Mandal ga washkè !	",
        "60 Ngray civèɗ movar nshèffè	",
        "61 Ko wawa a nshèffè mɓua’a	",
        "62 Slambaɗa, mizlinè Yèsu a n’ndev di ɓai	",
        "63 Mwuɗitepa…	",
        "64 Yèsu a tsi ntamagi ndav nga	",
        "65 A ndohi kin pela ɗè ?	",
        "66 Ha m’metsi nga	",
        "67 Washkè, ka njèy ma Yèsu	",
        "68 Ndo m’mɓer tambaki a bèhè	",
        "69 Yèsu a sun civèɗ	",
        "70 Va-nju ma m’mbel ndo Yèsu Krist	",
        "71 Va-fa na gèɗ a ma Yèsu	",
        "72 Kinè, kin ndohi nderɗe Zhiklè krèh	",
        "73 Zhiklè a ɓer skwi tèlèba	",
        "74 Movar man i ndia, movar nshèffè	",
        "75 Yowa, ara Daniel	",
        "76 Woba ndo	",
        "77 Nzlembaɗ Yèsu, nzlembaɗ mbia’a	",
        "78 Pierre te wurom	",
        "79 Va-pu di sèi a Yèsu !	",
        "80 Va-slambaɗa a Yèsu	",
        "81 Nshèffè mɓua’a a gèɗ ndohi tèlè	",
        "82 Ko ahngwa ahngwa a gèɗ herkeda	",
        "83 Zhiklè a bèhè ndohai	",
        "84 Zhiklè a woy herkeda	",
        "85 I woy man i rka ka	",
        "86 Fali ga i va na Yèsu	",
        "87 Yèsu, i herda ka va	",
        "88 I hér mwoy-ndo ngaya	",
        "89 Ndav ga nkezla	",
        "90 Yèsu nga shkè a sam ngaya	",
        "91 Ndohai 5000	",
        "92 Nza a tsagi ga	",
        "93 Yèsu, herde nga, a sam ngaya	",
        "94 Yèsu ndo m’mbel ndohai, i woya’a	",
        "95 Zhiklè nga shid gèɗ	",
        "96 Yèsu a pra nga malai	",
        "97 Zhiklè Bab nga te géɗè’a	",
        "98 Zhiklè mbia’a nga slébèrdè ka	",
        "99 Ntilyè a mali ga tèlèba wa ?	",
        "100 T’hwaɗ ki mamokwa’a	",
        "101 Ta yu ndo m’mbel ndo a patsna	",
        "102 Skwi nhél sam	",
        "103 Vo-washkè a sam ndo m’mbel ndo	",
        "104 Ka Zhiklè, ndha nga a Mèzhèɓ ngaya	",
        "105 A patsna ta yu Yèsu Kristi	",
        "106 Ma mbela’a man i tsena’a	",
        "107 M’metsi a zlèzlèmè a gèɗ herkeda	",
        "108 Zhiklè nga shid gèɗ	",
        "109 Yèsu a m’mets na ma	",
        "110 Vo-washkè, va-ngwod ndav kinè !	",
        "111 Dalahimam ga vo-washkè	",
        "112 Skwi mwuffè te ndav ga	",
        "113 Ntétékè ara skwi ambalai	",
        "114 Yèsu a n’ngul m’metsi a patsna	",
        "115 Ngodokoy a sam Bab nga	",
        "116 Yèsu a mshkè, a m’mets na	",
        "117 Maya maya, vaɗ a shkè	",
        "118 Yèsu Bai a gèɗ bihai	",
        "119 Do, a ka gaɗa ta tèlè	",
        "120 Yèsu Bi m’mbel ndo klèng, nya ma	",
        "121 Washkè tsena da’ai Zhiklè !	",
        "122 Ndo m’mbel ndo man i co a ndav	",
        "123 Kin rka nrkedi cè ?	",
        "124 Vo-washkè ndo tèlè	",
        "125 Mèzhèɓ Zhiklè man nkezla’a	",
        "126 Gu susai…	",
        "127 Yèsu civèɗ nshèffè ga	",
        "128 Yèsu, kra Bi Zhiklè	",
        "129 A pats man Bi Yèsu	",
        "130 Nga da ga na mbali a Bi nga	",
        "131 Zhiklè a woy ndo nhadka ma	",
        "132 Nga ɓica va a haha	",
        "133 Wa ndohi Yèsu Kristi, ngo-gokoy malwuɗai	",
        "134 Zhiklè a woy nga	",
        "135 Ko wawa a nshèffè mɓua’a	",
        "136 Ndo man a woy Yèsu	",
        "137 Zhiklè a ntsu kokwar Egypte	",
        "138 Herkeda haha	",
        "139 Wa Zhiklè !	",
        "140 Yèsu a woy ndo	",
        "141 I gu zlau a géɗ Adam a Eve	",
        "142 Va-war Yèsu kra Zhiklè	",
        "143 Vo-washkè, va-tsena ma Zhiklè	",
        "144 Zhiklè a woy mandazlihai	",
        "145 Wa Bi Zhiklè	",
        "146 Ndo nwush tser skwai	",
        "147 Dimèsh Marai a géɗ Noel	",
        "148 Zhiklè a ngau giɗfèk, a ngau géɗ herkeda	",
        "149 Iyè a sam nangwa, man Yèsu a shkè deɓa ?	",
        "150 Bi Zhiklè a rka kinè te matakwan	",
        "151 Wa Yèsu, kra Zhiklè	",
        "152 A mshkè herkeda a géɗ mali nga	"
    )


}
